let body = document.body;
body.addEventListener("keydown",(dets)=>{
  let h1 = document.querySelector("h1");
  h1.innerHTML=dets.code;
  if(dets.code === 'KeyA') new Audio('./one.mp3').play()
  else if(dets.code==='KeyS') new Audio('./two.mp3').play()
  else if(dets.code==='KeyD') new Audio('./three.mp3').play()
  else if(dets.code==='KeyF') new Audio('./four.mp3').play()
  else if(dets.code==='KeyG') new Audio('./five.mp3').play()
  else if(dets.code==='KeyH') new Audio('./six.mp3').play()
  else if(dets.code==='KeyJ') new Audio('./seven.mp3').play()
  else if(dets.code==='KeyK') new Audio('./eight.mp3').play()
  else if(dets.code==='KeyL') new Audio('./nine.mp3').play()
  else if(dets.code==='KeyZ') new Audio('./ten.mp3').play()
  else if(dets.code==='KeyX') new Audio('./nine.mp3').play()
  else if(dets.code==='KeyC') new Audio('./eight.mp3').play()
  else if(dets.code==='KeyV') new Audio('./seven.mp3').play()
  else if(dets.code==='KeyB') new Audio('./six.mp3').play()
  else if(dets.code==='KeyN') new Audio('./five.mp3').play()
  else if(dets.code==='KeyN') new Audio('./four.mp3').play()
  else if(dets.code==='KeyM') new Audio('./three.mp3').play()
  else if(dets.code==='KeyB') new Audio('./two.mp3').play()
  else if(dets.code==='KeyQ') new Audio('./one.mp3').play()
  else if(dets.code==='KeyW') new Audio('./ten.mp3').play()
  else if(dets.code==='KeyE') new Audio('./nine.mp3').play()
  else if(dets.code==='KeyR') new Audio('./eight.mp3').play()
  else if(dets.code==='KeyT') new Audio('./seven.mp3').play()
  else if(dets.code==='KeyY') new Audio('./six.mp3').play()
  else if(dets.code==='KeyU') new Audio('./five.mp3').play()
  else if(dets.code==='KeyI') new Audio('./four.mp3').play()
  else if(dets.code==='KeyO') new Audio('./three.mp3').play()
  else if(dets.code==='KeyP') new Audio('./two.mp3').play()

})